# [START app_yaml]
runtime: nodejs8
instance_class: F4
automatic_scaling:
  max_instances: 10
  max_concurrent_requests: 5
  target_throughput_utilization: 0.7
handlers:
  - url: /robots\.txt
    static_files: static/robots.txt
    upload: static/robots.txt
# [END app_yaml]
